#!/bin/zsh

mkdir gdb-build
mkdir gdb-install
cd gdb-build
../gdb-${V_GDB}/configure \
    --host=i686-w64-mingw32 \
    --prefix=/c/Users/Public/tinkerboard \
    --target=arm-tinkerboard-linux-gnueabihf \
    --with-sysroot=/c/Users/Public/tinkerboard/arm-tinkerboard-linux-gnueabihf \
    --enable-plugins \
    --disable-nls \
    --with-pkgversion="GDB for the Asus Tinkerboard" \
    --disable-nls \
    --with-expat \
    --with-libexpat-prefix=$PWD/../expat-install/usr/local/
# --with-python=$PWD/../makes/python-config-gdb
make -j10
DESTDIR=$PWD/../gdb-install make install
cd ../gdb-install
i686-w64-mingw32-strip --remove-section=.comment --remove-section=.note --strip-unneeded **/*.exe
